### ISSUE TITLE
attributes trait_type or value error

### ISSUE THREAD

**Issue by selimerunkut** [nishantrpai/rarity-score#1]
This attributes do not work with the app

```
"attributes": [
      {
        "trait_type": "Argenziano Territory",
        "value": "The Hood"
      },
      {
        "trait_type": "Skeleton",
        "value": "BodyAfrican"
      },
      {
        "trait_type": "Tuxedo Shirt",
        "value": "TuxedoShirt"
      },
      {
        "trait_type": "Tuxedo Jacket",
        "value": "TuxedoJacket"
      },
      {
        "trait_type": "Consigliere Weapons",
        "value": "HandBible"
      },
      {
        "trait_type": "Consigliere Eyes",
        "value": "EyesAngryBrown"
      },
      {
        "trait_type": "Consigliere Ring",
        "value": "PinkyRingDiamondGold"
      },
      {
        "trait_type": "Closed Mouth",
        "value": "MouthSmirk"
      },
      {
        "trait_type": "Consigliere Hair",
        "value": "HairBaldGrey"
      },
      {
        "trait_type": "Consigliere Glasses",
        "value": "EyewearGoldSpectacles"
      },
      {
        "trait_type": "Argenziano",
        "value": "Argenziano"
      }
    ]
```
    
or this:

```
 
"attributes": [
      {
        "trait_type": "Don Argenziano",
        "value": "Don AlessandroBigAlArgenziano"
      },
      {
        "trait_type": "Argenziano",
        "value": "Argenziano"
      }
    ]
```

Getting Error:

```
1
set nfts rank
TypeError: Cannot read property 'sum' of undefined
    at set_missing_traits (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:221:40)
    at set_trait_rarity (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:264:5)
    at getNFT (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:329:5)
    at /Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:343:26
    at Array.map (<anonymous>)
    at set_nfts_rank (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:343:15)
    at Object.RHsr (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:346:1)
    at __webpack_require__ (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:23:31)
    at Module.EVir (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:110:68)
    at __webpack_require__ (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/api/nfts.js:23:31)
FetchError: invalid json response body at http://localhost:3000/api/nfts? reason: Unexpected token I in JSON at position 0
    at /Users/selimerunkut/dev/lafamiglia/rarity-score/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getNFTs (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/index.js:117:16)
    at async Function.module.exports.RNiq.Home.getInitialProps (/Users/selimerunkut/dev/lafamiglia/rarity-score/.next/server/pages/index.js:875:7)
    at async loadGetInitialProps (/Users/selimerunkut/dev/lafamiglia/rarity-score/node_modules/next/dist/shared/lib/utils.js:69:19)
    at async Object.loadGetInitialProps (/Users/selimerunkut/dev/lafamiglia/rarity-score/node_modules/next/dist/shared/lib/utils.js:63:28)
    at async Object.renderToHTML (/Users/selimerunkut/dev/lafamiglia/rarity-score/node_modules/next/dist/server/render.js:314:17)
    at async doRender (/Users/selimerunkut/dev/lafamiglia/rarity-score/node_modules/next/dist/server/next-server.js:1144:38)
    at async /Users/selimerunkut/dev/lafamiglia/rarity-score/node_modules/next/dist/server/next-server.js:1236:28
    at async /Users/selimerunkut/dev/lafamiglia/rarity-score/node_modules/next/dist/server/response-cache.js:64:36 {
  type: 'invalid-json'
}
```

**Comment by nishantrpai** [comment]
Could you share the entire JSON selim, also you can use [this ](https://raw.githubusercontent.com/nishantrpai/rarity-score/main/data/collection.json) for reference

**Comment by tizzle** [comment]
Hey, this happens because the punks collection used in the example has a trait called `type`.

That was hardcoded in several functions in the util 'nfts.js':
`set_missing_traits`, `set_nft_rarity`, `calculate_attribute_rarity`

This has to be changed to picking a valid trait, for example like this: 

```
const [firstTrait] = Object.keys(all_traits)
const totaltraits = all_traits[firstTrait].sum;
```

**Comment by selimerunkut** [comment]
Thanks, had changed the code to accommodate our collection and it worked great.
Forgot to close this issue, after that

**Comment by nishantrpai** [comment]
> Hey, this happens because the punks collection used in the example has a trait called `type`.
> 
> That was hardcoded in several functions in the util 'nfts.js': `set_missing_traits`, `set_nft_rarity`, `calculate_attribute_rarity`
> 
> This has to be changed to picking a valid trait, for example like this:
> 
> ```
> const [firstTrait] = Object.keys(all_traits)
> const totaltraits = all_traits[firstTrait].sum;
> ```

Interesting. @selimerunkut was this the issue or something else?

**Comment by Goldo02** [comment]
was this

**Comment by h0rizons** [comment]
> Hey, this happens because the punks collection used in the example has a trait called `type`.
> 
> That was hardcoded in several functions in the util 'nfts.js': `set_missing_traits`, `set_nft_rarity`, `calculate_attribute_rarity`
> 
> This has to be changed to picking a valid trait, for example like this:
> 
> ```
> const [firstTrait] = Object.keys(all_traits)
> const totaltraits = all_traits[firstTrait].sum;
> ```

What exactly do you chanve in the NFTs.js? Been struggling with this.

**Comment by nishantrpai** [comment]
Yes, I've pushed a fix for this. Sorry for the trouble, didn't realise 'type' isn't a common trait in every NFT. 

Currently uses collection.length, assumption is there would be one common trait in every collection.

**Comment by nishantrpai** [comment]
will repon if this issue persists or you feel it still persists, please rebase with main branch.
